### ISSUE TITLE
`/tokens/:tokenId/send` sending other Token with auto waitForConfirmation

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/playground#135]
#### What would you like to be added:

https://github.com/DeFiCh/playground/blob/c9c0128ad2dee61e359d1442b976680a39689eb7/src/module.api/wallet.controller.ts#L51-L52

Currently, only `tokenId=0` is supported due to the complexity of sending DFI Token as RPC block this type of transaction.

#### Why is this needed:

To remove waiting on cypress tests, to allow a more nature testing paradigm.

**Comment by thedoublejay** [comment]
Might help on improvement. API fails often on Cypress - https://dashboard.cypress.io/projects/oqk3fk/runs/1430/test-results/cf6ffcea-a334-45c1-8d33-09e4fa9e7a35?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

**Comment by fuxingloh** [comment]
> Might help on improvement. API fails often on Cypress - https://dashboard.cypress.io/projects/oqk3fk/runs/1430/test-results/cf6ffcea-a334-45c1-8d33-09e4fa9e7a35?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

I will prioritize this, the flakiness is pretty annoying.
