### ISSUE TITLE
`OracleBot` with random `SetOracleData`

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/playground#136]
#### What would you like to be added:

`OracleBot`, for playground to have a lively oracle responding and aggregation price ticker.

Via `@Interval(n)` with different price characteristics to test different scenarios.

**Comment by monstrobishi** [comment]
@fuxingloh can you briefly list the different scenarios that you would like the prices to exhibit?

For a start I have:
- Always causes liquidation
- Stable price, never changes
- Crab market (slight variation around a stable price)

**Comment by fuxingloh** [comment]
- Always going up
- Always going down 
- 25% up/down jump every 5 block
- 50% every 5 block 
- 75%
- 100%

Any other patterns works too
