### ISSUE TITLE
create a pair with low/empty liquidity

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/playground#388]
#### What would you like to be added:
Related: https://github.com/DeFiCh/wallet/issues/2033

We would like to have the ability in the LW to add any liquidity amount in case pair doesn't have enough. Currently, it displays as NaN due to price ratio computation. 

Once we have added this pair, an e2e test can be added on the LW to enable adding of any amounts in case prices are not valid.

**Comment by fuxingloh** [comment]
@thedoublejay do you just need a pair with zero liquidity?

**Comment by thedoublejay** [comment]
@fuxingloh Ok we can have that as well
